version: '3.8'

services:
  prefect:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs
    environment:
      - PREFECT_API_URL=http://localhost:4200
      - GOOGLE_APPLICATION_CREDENTIALS=/app/configs/gcp_credentials.json
    ports:
      - "8080:8080"
    command: ["prefect", "server", "start"]

  beam:
    image: apache/beam_python3.8_sdk:latest
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs
    command: ["python", "/app/src/prefect_gcp/flows/beam_pipeline.py"]