development:
  project_name: "prefect-gcp"
  environment: "development"
  logging:
    level: "DEBUG"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  gcp:
    project_id: "your-gcp-project-id"
    region: "us-central1"
    bucket_name: "your-gcs-bucket-name"
  beam:
    runner: "DataflowRunner"
    temp_location: "gs://your-gcs-bucket-name/temp"
    staging_location: "gs://your-gcs-bucket-name/staging"
  database:
    host: "localhost"
    port: 5432
    user: "your-db-user"
    password: "your-db-password"
    dbname: "your-db-name"