environment: staging
project:
  name: prefect-gcp
  description: A prototype project utilizing Apache Beam and Prefect on Google Cloud Platform.
  version: 0.1.0
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
gcp:
  project_id: your-gcp-project-id
  region: us-central1
  bucket_name: your-gcs-bucket-name
  service_account: path/to/your/service-account.json
beam:
  runner: DataflowRunner
  temp_location: gs://your-gcs-bucket-name/temp
  staging_location: gs://your-gcs-bucket-name/staging
  job_name: prefect-gcp-job
  autoscaling_algorithm: THROUGHPUT_BASED
  max_num_workers: 10
  worker_machine_type: n1-standard-1
  disk_size_gb: 30
  save_main_session: true
  streaming: false
  additional_options:
    --max_num_workers: 10
    --worker_machine_type: n1-standard-1
    --disk_size_gb: 30